# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"resource_to_string": "00_core.ipynb",
         "print_resource": "00_core.ipynb",
         "create_app": "50_flask_hello_world.ipynb",
         "IN_COLAB": "51_flask_client_py_readme.ipynb",
         "smart_defaults": "51_flask_client_py_readme.ipynb",
         "app": "51_flask_client_py_readme.ipynb",
         "index": "51_flask_client_py_readme.ipynb",
         "callback": "51_flask_client_py_readme.ipynb",
         "logout": "51_flask_client_py_readme.ipynb",
         "reset": "51_flask_client_py_readme.ipynb"}

modules = ["core.py",
           "flask_hello_world.py",
           "flask_client_py_readme.py"]

doc_url = "https://pete88b.github.io/smart-on-fhir-client-py-demo/"

git_url = "https://github.com/pete88b/smart-on-fhir-client-py-demo/tree/main/"

def custom_doc_links(name): return None
