# AUTOGENERATED! DO NOT EDIT! File to edit: 51_flask_client_py_readme.ipynb (unless otherwise specified).

__all__ = ['smart_defaults', 'app', 'index', 'callback', 'logout', 'reset']

# Cell
import logging
from fhirclient import client
from fhirclient.models.medication import Medication
from fhirclient.models.medicationrequest import MedicationRequest
from fhirclient.models.patient import Patient
from flask import Flask, request, redirect, session, url_for

# Cell
smart_defaults = {
    'app_id': 'my_web_app',
    'api_base': 'http://wildfhir4.aegis.net/fhir4-0-0',
#     'api_base': 'http://hapi.fhir.org/baseR4',
    'redirect_uri': 'http://localhost:8000/fhir-app/',
}

app = Flask(__name__)
app.config.from_mapping(
    # a default secret that should be overridden by instance config
    SECRET_KEY="dev"
)

# Cell
def _save_state(state):
    session['state'] = state

def _get_smart():
    state = session.get('state')
    if state:
        return client.FHIRClient(state=state, save_func=_save_state)
    else:
        return client.FHIRClient(settings=smart_defaults, save_func=_save_state)

def _logout():
    if 'state' in session:
        smart = _get_smart()
        smart.reset_patient()

def _reset():
    if 'state' in session:
        del session['state']

def _get_prescriptions(smart):
    bundle = MedicationRequest.where({'patient': smart.patient_id}).perform(smart.server)
    pres = [be.resource for be in bundle.entry] if bundle is not None and bundle.entry is not None else None
    if pres is not None and len(pres) > 0:
        return pres
    return None

def _get_medication_by_ref(ref, smart):
    med_id = ref.split("/")[1]
    return Medication.read(med_id, smart.server).code

def _med_name(med):
    if med.coding:
        name = next((coding.display for coding in med.coding if coding.system == 'http://www.nlm.nih.gov/research/umls/rxnorm'), None)
        if name:
            return name
    if med.text and med.text:
        return med.text
    return "Unnamed Medication(TM)"

def _get_med_name(prescription, client=None):
    if prescription.medicationCodeableConcept is not None:
        med = prescription.medicationCodeableConcept
        return _med_name(med)
    elif prescription.medicationReference is not None and client is not None:
        med = _get_medication_by_ref(prescription.medicationReference.reference, client)
        return _med_name(med)
    else:
        return 'Error: medication not found'

# Cell
def _get_patients(smart):
    bundle = Patient.where(struct={}).perform(smart.server)
    patients = [be.resource for be in bundle.entry] if bundle is not None and bundle.entry is not None else None
    if patients is not None and len(patients) > 0:
        return patients
    return None

# Cell
@app.route('/')
@app.route('/index.html')
def index():
    """ The app's main page.
    """
    smart = _get_smart()
    body = "<h1>Hello</h1>"

    if request.args.get('patient_id') is not None:
        smart.patient_id = request.args.get('patient_id')
    print('ready',smart.ready,'patient_id',smart.patient_id,'patient',smart.patient)

    def _format_name(patient):
        return smart.human_name(patient.name[0] if patient.name and len(patient.name) > 0 else 'Unknown')

    def _format_patient(patient):
        s = f'{patient.id} {_format_name(patient)} '
        if patient.birthDate is not None: s += patient.birthDate.isostring
        return s

    if smart.ready and smart.patient is not None: # "ready" may be true but the access token may have expired, making smart.patient = None
        name = _format_name(smart.patient)

        # generate simple body text
        body += "<p>You are authorized and ready to make API requests for <em>{0}</em>.</p>".format(name)
        pres = _get_prescriptions(smart)
        if pres is not None:
            body += "<p>{0} prescriptions: <ul><li>{1}</li></ul></p>".format("His" if 'male' == smart.patient.gender else "Her", '</li><li>'.join([_get_med_name(p,smart) for p in pres]))
        else:
            body += "<p>(There are no prescriptions for {0})</p>".format("him" if 'male' == smart.patient.gender else "her")
        body += """<p><a href="/logout">Change patient</a></p>"""
    else:
        auth_url = smart.authorize_url
        if auth_url is not None:
            body += """<p>Please <a href="{0}">authorize</a>.</p>""".format(auth_url)
        else:
            body += """<p>Running against a no-auth server.<br>"""
            for patient in _get_patients(smart):
                # id name dob
                body += "<hr><a href='{0}'>Select patient</a> {1}".format(
                    url_for('index', patient_id=patient.id),
                    _format_patient(patient))
#             body += '<br>'.join(resource_to_string(_get_patients(smart)))
        body += """<p><a href="/reset" style="font-size:small;">Reset</a></p>"""
    return body

# Cell
@app.route('/fhir-app/')
def callback():
    """ OAuth2 callback interception.
    """
    smart = _get_smart()
    try:
        smart.handle_callback(request.url)
    except Exception as e:
        return """<h1>Authorization Error</h1><p>{0}</p><p><a href="/">Start over</a></p>""".format(e)
    return redirect('/')

# Cell
@app.route('/logout')
def logout():
    _logout()
    return redirect('/')

# Cell
@app.route('/reset')
def reset():
    _reset()
    return redirect('/')

# Cell
try: from nbdev.imports import IN_NOTEBOOK
except: IN_NOTEBOOK = False
if '__main__' == __name__ and not IN_NOTEBOOK:
    logging.basicConfig(level=logging.DEBUG)
    app.run(debug=True, port=8000)